Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	articles_indexs
	1	cat_indexs
	1	fusion
	1	global_alignment
	1	request
	5

[Tue Mar 24 18:52:13 2020]
rule articles_indexs:
    input: dataset/CaL/article/fphys-07-00481.pdf
    output: dataset/CaL/articles_indexs/fphys-07-00481.txt
    jobid: 4
    wildcards: channel=CaL, article=fphys-07-00481

[Tue Mar 24 18:52:15 2020]
Finished job 4.
1 of 5 steps (20%) done

[Tue Mar 24 18:52:15 2020]
rule cat_indexs:
    input: dataset/CaL/articles_indexs/fphys-07-00481.txt
    output: indexs.txt
    jobid: 3

Removing temporary output file dataset/CaL/articles_indexs/fphys-07-00481.txt.
[Tue Mar 24 18:52:15 2020]
Finished job 3.
2 of 5 steps (40%) done

[Tue Mar 24 18:52:15 2020]
rule fusion:
    input: indexs.txt, fixed.txt
    output: workflow/clear_indexs.csv
    jobid: 2

Removing temporary output file indexs.txt.
[Tue Mar 24 18:52:17 2020]
Finished job 2.
3 of 5 steps (60%) done

[Tue Mar 24 18:52:17 2020]
rule request:
    input: workflow/clear_indexs.csv
    output: workflow/all_sequences.fasta
    jobid: 1

Removing temporary output file workflow/clear_indexs.csv.
[Tue Mar 24 18:52:19 2020]
Finished job 1.
4 of 5 steps (80%) done

[Tue Mar 24 18:52:19 2020]
rule global_alignment:
    input: workflow/all_sequences.fasta
    output: workflow/all_sequences.aln
    jobid: 0

[Tue Mar 24 18:52:21 2020]
Error in rule global_alignment:
    jobid: 0
    output: workflow/all_sequences.aln

RuleException:
CalledProcessError in line 33 of /home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/Snakefile:
Command 'set -euo pipefail;  jupyter-nbconvert --execute  --to notebook --ExecutePreprocessor.timeout=-1 '/home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/.snakemake/scripts/tmpw6yde1yd.global_alignment.ipynb'' returned non-zero exit status 1.
  File "/home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/Snakefile", line 33, in __rule_global_alignment
  File "/home/mark/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/mark/Рабочий стол/bioinf/urfu_bioinf_2020/.snakemake/log/2020-03-24T185213.041472.snakemake.log
